Add item requests
VitalyKapustin-git/java-shareit pull request #3
Opened 2022-10-26 03:30 UTC by VitalyKapustin-git

- added functionallity for item request;
- added tests;

2022-10-27 04:43 UTC, NikolaiDem requested changes

2022-10-27 04:43 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/dao/BookingRepository.java
> +@Repository
Аннотация не нужна, этот интерфейс бином не станет)

2022-10-27 04:43 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> -        bookingDto.setItem(ItemMapper.toItemDto(itemRepository.getItemById(booking.getItemId())));
Теперь маппер стал не совсем полноценным. Часть маппинга выполняется здесь, а часть в других местах. Лучше сделать поля Item и User в Booking-е и смапить их на ItemDto и UserDto в BookingDto здесь.

2022-10-27 04:43 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long requestId;
Так как у запроса есть описание, заказчик и другие параметры, то удобнее работать с объектом ItemRequest. Поэтому вместо requestId лучше создать ItemRequest.

2022-10-27 04:43 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> + * TODO Sprint add-item-requests.
TODO пишем, когда есть что делать, а здесь все готово)

2022-10-27 04:43 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +public class ItemRequest {
Все поля private

2022-10-27 04:43 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    Long requestorId;
Лучше использовать User вместо requestorId.

2022-10-27 04:43 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +    public ItemRequestDto create(@Valid @RequestBody ItemRequest itemRequest,
При общении с внешним миром лучше использовать структуры DTO (ItemRequestDto)

2022-10-27 04:43 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    Long id;
Все поля private

2022-10-27 04:43 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/dto/ItemRequestDto.java
> +    Long requestorId;
Это поле не используется ни для запроса ни для ответа)

2022-10-27 04:43 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestService.java
> +    public ItemRequestDto create(ItemRequest itemRequest, Long requestorId);
В интерфейсе все методы по умолчанию public. Явно указывать не нужно.

2022-10-27 04:43 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
> +    @NotBlank
Валидацию лучше делать на классах DTO, потому что контроллеры обмениваются через них с внешним миром.

2022-10-27 04:43 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    public ItemRequestDto create(ItemRequest itemRequest, Long requestorId) {
Здесь должно быть ItemRequestDto, потому и проверка if (itemRequest.getDescription().isBlank()){} будет лишней, потому что невалидный Dto не пройдет контроллер.

2022-10-27 04:43 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +                    itemRequestDto.setItems(itemRepository.getItemsByRequestId(v.getId()).stream()
Здесь выполнятся лишние запросы к БД. Лучше одним запросом вытащить все Item-s для всех запросов, а уже здесь распределить их по ItemRequest-ам.
Аналогично для getOtherUsersRequests(...)

2022-10-27 04:43 UTC, NikolaiDem commented on src/main/resources/schema.sql
> +    id
Привести к читаемому виду (каждый столбец на своей строке)

2022-10-27 04:43 UTC, NikolaiDem commented on src/test/java/ru/practicum/shareit/booking/BookingServiceJPATest.java
> +    private final EntityManager em;
Так как тесты предназначаются для проверки работы репозитория, то лучше использовать его вместо менеджера сущностей. Проверка будет заключаться в том, чтобы сначала сохранить некоторые объекты, а потом вызывать кастомные запросы из репозитория и сравнить их результат с ожидаемым)

2022-10-27 11:28 UTC, VitalyKapustin-git commented on src/main/resources/schema.sql
> +    id
@NikolaiDem Привет. Вот тут тебя не совсем понял. У меня же вроде так и есть? Или речь про добавление табуляций?

[скрин как у меня](https://imgur.com/a/bLUYzeM)

2022-10-28 00:51 UTC, VitalyKapustin-git commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +    public ItemRequestDto create(ItemRequest itemRequest, Long requestorId) {
Здесь проверка не для того чтобы проверить, а для того, чтобы выкинуть свой exception для прохождения тестов в постмане с человеческим текстом).
Убрал.

2022-10-28 17:28 UTC, VitalyKapustin-git commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long requestId;
@NikolaiDem Этот момент остался единственный без правок. 
Слишком много логики переписывать, концов с концами не сыщешь.
Если можно, этот момент я бы уже оставил как есть, с учетом того, что остальные требования удовлетворены.

2022-10-29 12:23 UTC, NikolaiDem requested changes

2022-10-29 12:23 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
>  @Data
Удалить @Data для всех сущностей. 
Методы equals и hashcode переопределять нет необходимости.

2022-10-29 12:23 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        List<ItemDto> items = itemRepository.getItemsByRequestIdIn(itemRequestsId).stream()
Лучше в мапу преобразовать, чтобы избежать .filter(i -> i.getRequestId() == v.getId())

2022-10-29 12:23 UTC, NikolaiDem commented on src/test/java/ru/practicum/shareit/item/ItemServiceUnitTest.java
> +package ru.practicum.shareit.item;
Добавить тест для ItemRepository на проверку кастомных запросов.

2022-10-29 12:23 UTC, NikolaiDem commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +package ru.practicum.shareit.booking;
Добавить тесты для мапперов.

2022-10-29 12:28 UTC, NikolaiDem commented on src/main/resources/schema.sql
> +    id
Теперь все окей) Строки были разбиты по словам.

2022-10-29 12:28 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Long requestId;
Так как используется только в маппере. оставим так.

2022-10-30 20:02 UTC, VitalyKapustin-git commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +package ru.practicum.shareit.booking;
Покрыл в юнит-тестах

2022-10-31 07:22 UTC, NikolaiDem approved these changes

2022-11-01 19:30 UTC, merged